
title: Collecting Dust
email: fhanson@cloud-mgmt.com
logo: /static/self_portrait.png
description: Collection of links and tidbits for Franklin Hanson
baseurl: ''
url: 'https://cloud-mgmt.com'
twitter_username: franklinhanson1
github_username: fhanson
linkedin_username: franklin-hanson
keybase_username: fhanson
google_tagmanager: GTM-T6MDCH4
theme: minima
plugins:
  - jekyll-feed
